// <auto-generated />
using GestionMedic.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionMedic.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GestionMedic.model.categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("categorie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PrimaryKey_Numero");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GestionMedic.model.medicaments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_categorie")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("prix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PrimaryKey_Numero");

                    b.HasIndex("id_categorie");

                    b.ToTable("medicaments");
                });

            modelBuilder.Entity("GestionMedic.model.medicaments", b =>
                {
                    b.HasOne("GestionMedic.model.categories", "categories")
                        .WithMany("medicaments")
                        .HasForeignKey("id_categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categories");
                });

            modelBuilder.Entity("GestionMedic.model.categories", b =>
                {
                    b.Navigation("medicaments");
                });
#pragma warning restore 612, 618
        }
    }
}
